// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3np3CTbdfVt2ZFp08-Uk_BZV1ZyWlfw8',
    appId: '1:477360753977:web:7bf1ca3bb15c09ae09ece8',
    messagingSenderId: '477360753977',
    projectId: 'shoppingapp-25bdc',
    authDomain: 'shoppingapp-25bdc.firebaseapp.com',
    storageBucket: 'shoppingapp-25bdc.appspot.com',
    measurementId: 'G-XGQFPZLD6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxFOKOeWyuYS4c9ltmB5F-wcBqiRYrISA',
    appId: '1:477360753977:android:cee0cf62105e107e09ece8',
    messagingSenderId: '477360753977',
    projectId: 'shoppingapp-25bdc',
    storageBucket: 'shoppingapp-25bdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC38OXmawnUzlEB6kniPSaecIPxjjQ3Hvk',
    appId: '1:477360753977:ios:a2031a77478f5e6d09ece8',
    messagingSenderId: '477360753977',
    projectId: 'shoppingapp-25bdc',
    storageBucket: 'shoppingapp-25bdc.appspot.com',
    iosClientId: '477360753977-ap6kfhu5f96pkkghudqr5e5idkbm78f5.apps.googleusercontent.com',
    iosBundleId: 'com.siphowngom.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC38OXmawnUzlEB6kniPSaecIPxjjQ3Hvk',
    appId: '1:477360753977:ios:a2031a77478f5e6d09ece8',
    messagingSenderId: '477360753977',
    projectId: 'shoppingapp-25bdc',
    storageBucket: 'shoppingapp-25bdc.appspot.com',
    iosClientId: '477360753977-ap6kfhu5f96pkkghudqr5e5idkbm78f5.apps.googleusercontent.com',
    iosBundleId: 'com.siphowngom.shoppingApp',
  );
}
